
select * from taskTable;

CREATE TABLE taskTable (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    task_Name VARCHAR(200) NOT NULL,
    completedBy DATE,
    checkBox BOOLEAN,
    bullets BOOLEAN,
    sub_Task1_Name VARCHAR(200),
    sub_CompletedBy1 DATE,
    sub_Task1_Check BOOLEAN,
    sub_Task2_Name VARCHAR(200),
    sub_CompletedBy2 DATE,
    sub_Task2_Check BOOLEAN,
    sub_Task3_Name VARCHAR(200),
    sub_CompletedBy3 DATE,
    sub_Task3_Check BOOLEAN,
    sub_Task4_Name VARCHAR(200),
    sub_CompletedBy4 DATE,
    sub_Task4_Check BOOLEAN,
    sub_Task5_Name VARCHAR(200),
    sub_CompletedBy5 DATE,
    sub_Task5_Check BOOLEAN,
    sub_Task6_Name VARCHAR(200),
    sub_CompletedBy6 DATE,
    sub_Task6_Check BOOLEAN,
    sub_Task7_Name VARCHAR(200),
    sub_CompletedBy7 DATE,
    sub_Task7_Check BOOLEAN,
    sub_Task8_Name VARCHAR(200),
    sub_CompletedBy8 DATE,
    sub_Task8_Check BOOLEAN,
    sub_Task9_Name VARCHAR(200),
    sub_CompletedBy9 DATE,
    sub_Task9_Check BOOLEAN,
    sub_Task10_Name VARCHAR(200),
    sub_CompletedBy10 DATE,
    sub_Task10_Check BOOLEAN,
    description VARCHAR(1000)
    );

    INSERT INTO taskTable ( username, task_Name, completedBy, checkBox, bullets,
                       sub_Task1_Name, sub_CompletedBy1,
                       sub_Task2_Name, sub_CompletedBy2,
                       sub_Task3_Name, sub_CompletedBy3,
                       sub_Task4_Name, sub_CompletedBy4,
                       sub_Task5_Name, sub_CompletedBy5,
                       sub_Task6_Name, sub_CompletedBy6,
                       sub_Task7_Name, sub_CompletedBy7,
                       sub_Task8_Name, sub_CompletedBy8,
                       sub_Task9_Name, sub_CompletedBy9,
                       sub_Task10_Name, sub_CompletedBy10,
                       description)
       VALUES ( 'test','Complete Task Table', '2021-12-31','1','0',
               'sub task 1', '2021-12-01',
               'sub task 2', '2021-12-02',
               'sub task 3', '2021-12-03',
               'sub task 4', '2021-12-04',
               'sub task 5', '2021-12-05',
               'sub task 6', '2021-12-06',
               'sub task 7', '2021-12-07',
               'sub task 8', '2021-12-08',
               'sub task 9', '2021-12-09',
               'sub task 10', '2021-12-10',
               'I need to finish this before next week!');